# -*- coding: utf-8 -*-
"""scratchpad

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/empty.ipynb
"""
import streamlit as st
import pickle

# Load the model
with open('AQI Forecaster.pkl', 'rb') as f:
    model = pickle.load(f)

# Streamlit app
st.title('AQI Forecasting System')

if st.button('About'):
    st.write('This system predicts you the AQI in your place after 6 hours.')


st.write('Enter your input in the following fields')

time = st.text_input('Time: (e.g. 0, 1, 2, ... 23)')
pm_twofive = st.text_input('PM2.5 in micrograms per cubic meter:')
pm_ten = st.text_input('PM10 in  micrograms per cubic meter:')
co = st.text_input('CO in micrograms per cubic meter:')
so2 = st.text_input('SO2 in micrograms per cubic meter:')
no2 = st.text_input('NO2 in micrograms per cubic meter:')
o3 = st.text_input('O3 in in micrograms per cubic meter:')
aqi = st.text_input('Current AQI:')

if st.button('Forecast'):
    try:
        input_list = [time, pm_twofive, pm_ten, co, so2, no2, o3, aqi]
        prediction = model.predict([input_list])
        st.success(f'AQI after 6 hours: {prediction[0]}')

    except Exception as e :
        st.error(f"Error: {e}")