# -*- coding: utf-8 -*-
"""scratchpad

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/empty.ipynb
"""

import streamlit as st
import pickle

# Load the model
with open('cheat_clf.pkl', 'rb') as f:
    model = pickle.load(f)

# Streamlit app
st.title('Cheat Detector 1.0')
if st.button('Instructions'):
    st.write('Just simply answer the following questions.')

rep = st.text_input('On average, how much time (in minutes) to reply to your messages?')
args = st.text_input('On average, how many times do you argue with him in a week?')
emo = st.text_input('How much would you rate his emotional support towards you on a scale of 10?')
ext = st.text_input('How much of an extrovert is he on a scale of 10?')
fem = st.text_input('How many female friends does he have (approximately)?')
job = st.text_input('What is his job? [Mega Corporate: 5, Businessman: 4, Mid Corporate: 3, Jobless: 2]')
night = st.text_input('Does he have the habit of night outings? [Yes: 1, No: 0]')



if st.button('Forecast'):
    try:
        input_list = [rep, args, emo, ext, fem, job, night]
        prediction = model.predict([input_list])
        if prediction[0] == 1 :
            st.success('Unsafe. High probability that he will cheat.')

        else:
            st.success('Safe. High probability that he will not cheat.')
            st.balloons()
            st.snow()
    except Exception as e:
        st.error(f"Error:{e}")

if st.button('Data Summary') :
    try:
        st.write('Based on the data the model is trained on:')
        st.write(f'On average, a cheater takes 60 minutes to reply texts. Your boyfriend takes {rep} minutes.')
        st.write(f'On average, a cheater argues 3 times on a week. Your boyfriend do it {args} times.')
        st.write(f'On average, a cheater provides 5 unit emotional supports on a scale of 10. Your boyfriend provides {emo} unit.')
        st.write(f'On average, a cheater is 7 unit extrovert on a scale of 10. Your boyfriend is on {ext} unit.')
        st.write(f'On average, a cheater has 10 female friends, either single or mingle. Your boyfriend has {fem}.')
        st.write(f'A cheater is usually a businessman (rel_freq=0.3), a jobless (rel_freq=0.3), or a mega corporate (rel_freq=0.3).')
        st.write(f'Cheater usually do a lot of night outings (rel_freq=0.99)')

    except Exception as e:
        st.error(f'Error: {e}')
        st.write('Try inputing the values and forecasting. Then click Data Summary.')